// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://colndncnjyqwdglbwzuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvbG5kbmNuanlxd2RnbGJ3enVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyOTcyNDgsImV4cCI6MjA1Nzg3MzI0OH0.Ibb4H6UMGdg52r2tUl1dsnUk2fVvHY0QwIvvmNc-4_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);